package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.mechanisms.swerve.LegacySwerveRequest.SwerveDriveBrake;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.ForwardPerspectiveValue;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathConstraints;

import edu.wpi.first.hal.simulation.AnalogInDataJNI;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.SwerveModuleState;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.units.DistanceUnit;
import edu.wpi.first.units.Unit;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.sysid.SysIdRoutineLog.MotorLog;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.DeferredCommand;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.LimelightHelpers;
import frc.robot.RobotContainer;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.LaunchingTower.Vector2D;
import edu.wpi.first.epilogue.Logged;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
@Logged
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    private Field2d field = new Field2d();

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /** Swerve request to apply during robot-centric path following */
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();
    private final SwerveRequest.FieldCentricFacingAngle fieldCentric = new SwerveRequest.FieldCentricFacingAngle();
    // private final SwerveRequest. a = new SwerveRequest.FieldCentric();

    private final double fieldLength = 16.48;

    public final Pose2d shooterPose1Red = new Pose2d(14, 4, new Rotation2d(Units.degreesToRadians(180)));
    public final Pose2d shooterPose2Red = new Pose2d(10, 4, new Rotation2d(Units.degreesToRadians(0)));

    public final Pose2d climbRightRed = new Pose2d(15.15, 4.7, new Rotation2d(Units.degreesToRadians(180)));
    public final Pose2d climbLeftRed = new Pose2d(15, 4, new Rotation2d(Units.degreesToRadians(180)));

    public final Pose2d trenchRightCloseStartRed = new Pose2d(13.1, 7.4, new Rotation2d(Units.degreesToRadians(180)));
    public final Pose2d trenchRightFarEndRed = new Pose2d(10.8, 7.4, new Rotation2d(Units.degreesToRadians(180)));

    public final Pose2d trenchRightCloseEndRed = new Pose2d(13.1, 7.4, new Rotation2d(Units.degreesToRadians(180)));
    public final Pose2d trenchRightFarStartRed = new Pose2d(10.8, 7.4, new Rotation2d(Units.degreesToRadians(180)));

    public final Pose2d trenchLeftCloseStartRed = new Pose2d(13.1, .6, new Rotation2d(Units.degreesToRadians(180)));
    public final Pose2d trenchLeftFarEndRed = new Pose2d(10.8, .6, new Rotation2d(Units.degreesToRadians(180)));

    public final Pose2d trenchLeftCloseEndRed = new Pose2d(13.1, .6, new Rotation2d(Units.degreesToRadians(180)));
    public final Pose2d trenchLeftFarStartRed = new Pose2d(10.8, .6, new Rotation2d(Units.degreesToRadians(180)));

    public final Pose2d bumpLeftClose = new Pose2d(13.2, 2.5, new Rotation2d(Units.degreesToRadians(135)));
    public final Pose2d bumpLeftFar = new Pose2d(10.4, 2.5, new Rotation2d(Units.degreesToRadians(135)));

    public final Pose2d bumpRightClose = new Pose2d(13.2, 5.5, new Rotation2d(Units.degreesToRadians(225)));
    public final Pose2d bumpRightFar = new Pose2d(10.4, 5.5, new Rotation2d(Units.degreesToRadians(225)));

    public final Pose2d hubMidPoint = new Pose2d(12.07, 3.93,
            new Rotation2d(Units.degreesToRadians(0)));
    public final Pose2d blueHubMidPoint = new Pose2d(Constants.fieldLength - 12.07, 3.93,
            new Rotation2d(Units.degreesToRadians(0)));
    public final Pose2d redHubMidPoint = new Pose2d(12.07, 3.93,
            new Rotation2d(Units.degreesToRadians(0)));
    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    class Region {
        double x1;
        double y1;
        double x2;
        double y2;

        public Region(double x1, double y1, double x2, double y2) {
            this.x1 = x1;
            this.y1 = x1;
            this.x2 = x1;
            this.y2 = x1;
        }

        public boolean isInRegion(Pose2d pose) {
            var x = pose.getX();
            var y = pose.getY();

            var minX = Math.min(x1, x2);
            var minY = Math.min(y1, y2);

            var maxX = Math.max(x1, x2);
            var maxY = Math.max(y1, y2);

            return x < maxX && x > minX &&
                    y < maxY && x > minY;
        }

        public boolean isInRegion() {
            return isInRegion(getState().Pose);
        }
    }

    class SpeedRegion {
        double x1;
        double y1;
        double x2;
        double y2;
        double speed;

        public SpeedRegion(double x1, double y1, double x2, double y2, double speed) {
            this.x1 = x1;
            this.y1 = y1;
            this.x2 = x2;
            this.y2 = y2;
            this.speed = speed;
        }

        public boolean isInRegion(Pose2d pose) {
            var x = pose.getX();
            var y = pose.getY();

            var minX = Math.min(x1, x2);
            var minY = Math.min(y1, y2);

            var maxX = Math.max(x1, x2);
            var maxY = Math.max(y1, y2);

            return x < maxX && x > minX &&
                    y < maxY && y > minY;
        }

        public boolean isInRegion() {
            return isInRegion(getState().Pose);
        }

        public double getSpeed(Pose2d pose) {
            return isInRegion(pose) ? speed : 1;
        }

        public double getSpeed() {
            return isInRegion() ? speed : 1;
        }
    }

    class TargetRegion {
        double x1;
        double y1;
        double x2;
        double y2;
        LaunchingTower.Vector2D target;

        public TargetRegion(double x1, double y1, double x2, double y2, LaunchingTower.Vector2D target) {
            this.x1 = x1;
            this.y1 = y1;
            this.x2 = x2;
            this.y2 = y2;
            this.target = target;
        }

        public TargetRegion(double x1, double y1, double x2, double y2, Pose2d target) {
            this.x1 = x1;
            this.y1 = y1;
            this.x2 = x2;
            this.y2 = y2;
            this.target = new LaunchingTower.Vector2D(0, 0).fromPose2D(target);
        }

        public TargetRegion(Vector2D v1, Vector2D v2, LaunchingTower.Vector2D target) {
            this.x1 = v1.x;
            this.y1 = v1.y;
            this.x2 = v2.x;
            this.y2 = v2.y;
            this.target = target;
        }

        public TargetRegion(Vector2D v1, Vector2D v2, Pose2d target) {
            this.x1 = v1.x;
            this.y1 = v1.y;
            this.x2 = v2.x;
            this.y2 = v2.y;
            this.target = new LaunchingTower.Vector2D(0, 0).fromPose2D(target);
        }

        public boolean isInRegion(Pose2d pose) {
            var x = pose.getX();
            var y = pose.getY();

            var minX = Math.min(x1, x2);
            var minY = Math.min(y1, y2);

            var maxX = Math.max(x1, x2);
            var maxY = Math.max(y1, y2);

            return x < maxX && x > minX &&
                    y < maxY && y > minY;
        }

        public boolean isInRegion() {
            return isInRegion(getState().Pose);
        }

        public Vector2D getTarget(Pose2d pose) {
            return isInRegion(pose) ? target : new LaunchingTower.Vector2D(0, 0).fromPose2D(hubMidPoint);
        }
    }

    // public Region bumpBlueRegion = new Region(0, 0, 10, 10, .5);
    // public Region bumpRedRegion = new Region(0, 0, 10, 10, .5);
    public SpeedRegion[] speedRegions = new SpeedRegion[] {
            new SpeedRegion(10, 2.5, 20, 5.5, .1)
    };

    final TargetRegion blueRightMidRegion = new TargetRegion(blueHubMidPoint.getX(), blueHubMidPoint.getY(),
            Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY,
            new Vector2D(1, 1));
    final TargetRegion blueLeftMidRegion = new TargetRegion(blueHubMidPoint.getX(), blueHubMidPoint.getY(),
            Double.POSITIVE_INFINITY, Double.POSITIVE_INFINITY,
            new Vector2D(1, Constants.fieldWidth - 1));
    final TargetRegion blueAllianceRegion = new TargetRegion(blueHubMidPoint.getX(), Double.NEGATIVE_INFINITY,
            Double.NEGATIVE_INFINITY, Double.POSITIVE_INFINITY,
            new Vector2D(blueHubMidPoint.getX(), blueHubMidPoint.getY()));

    final TargetRegion redRightMidRegion = new TargetRegion(redHubMidPoint.getX(), redHubMidPoint.getY(),
            Double.NEGATIVE_INFINITY, Double.POSITIVE_INFINITY,
            new Vector2D(Constants.fieldLength - 1, Constants.fieldWidth - 1));
    final TargetRegion redLeftMidRegion = new TargetRegion(redHubMidPoint.getX(), redHubMidPoint.getY(),
            Double.NEGATIVE_INFINITY, Double.NEGATIVE_INFINITY,
            new Vector2D(Constants.fieldLength - 1, 1));
    final TargetRegion redAllianceRegion = new TargetRegion(redHubMidPoint.getX(), Double.NEGATIVE_INFINITY,
            Double.POSITIVE_INFINITY, Double.POSITIVE_INFINITY,
            new Vector2D(redHubMidPoint.getX(), redHubMidPoint.getY()));

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    public double getRegionSpeedMultiplier() {
        double speed = 1;
        for (int i = 0; i < speedRegions.length; i++) {
            speed = Math.min(speedRegions[i].getSpeed(), speed);
        }
        return speed;
    }

    public Vector2D getRegionTargetVector2D() {
        var speeds = getState().Speeds;
        var speedVector = new Vector2D(speeds.vxMetersPerSecond, speeds.vyMetersPerSecond);
        if (DriverStation.getAlliance().get() == Alliance.Blue) {
            if (blueLeftMidRegion.isInRegion()) {
                return blueLeftMidRegion.target.clone().addVector(speedVector);
            }
            if (blueRightMidRegion.isInRegion()) {
                return blueRightMidRegion.target.clone().addVector(speedVector);
            }
            return blueAllianceRegion.target.clone().addVector(speedVector);
        } else {
            if (redLeftMidRegion.isInRegion()) {
                return redLeftMidRegion.target.clone().addVector(speedVector);
            }
            if (redRightMidRegion.isInRegion()) {
                return redRightMidRegion.target.clone().addVector(speedVector);
            }
            return redAllianceRegion.target.clone().addVector(speedVector);
        }
    }

    public double fieldRelativeAngleToHubRad() {
        var robotPose = RobotContainer.drivetrain.getState().Pose;
        var shooterPose = robotPose.plus(new Transform2d(0, 0.2,
                Rotation2d.fromDegrees(180)));

        Vector2D target = RobotContainer.drivetrain.getRegionTargetVector2D();

        // var speeds = getState().Speeds;
        // target.x += speeds.vxMetersPerSecond * 1.0;
        // target.y += speeds.vyMetersPerSecond * 1.0;

        SmartDashboard.putString("dynamic target", target.toString());
        var targetX = target.x;
        var targetY = target.y;

        var relativeX = targetX - shooterPose.getX();
        var relativeY = targetY - shooterPose.getY();
        var angleRad = Math.atan2(relativeY, relativeX);

        if (angleRad > Math.PI) {
            angleRad = angleRad - 2 * Math.PI;
        }
        if (angleRad < -Math.PI) {
            angleRad = angleRad + 2 * Math.PI;
        }
        return angleRad;
    }

    public double robotOffsetAngleToHubRad() {
        var robotPose = RobotContainer.drivetrain.getState().Pose;
        var shooterPose = robotPose.plus(new Transform2d(0, 0.2, Rotation2d.fromDegrees(180)));

        Vector2D target = RobotContainer.drivetrain.getRegionTargetVector2D();
        SmartDashboard.putString("dynamic target", target.toString());
        var targetX = target.x;
        var targetY = target.y;

        var relativeX = targetX - shooterPose.getX();
        var relativeY = targetY - shooterPose.getY();
        var angleRad = Math.atan2(relativeY, relativeX) - shooterPose.getRotation().getRadians();

        if (angleRad > Math.PI) {
            angleRad = angleRad - 2 * Math.PI;
        }
        if (angleRad < -Math.PI) {
            angleRad = angleRad + 2 * Math.PI;
        }
        return angleRad;
    }

    public Pose2d getRegionTargetPose2D() {
        return getRegionTargetVector2D().toPose2D();
    }

    public Command zeroBotRotationCommand() {
        return runOnce(() -> {
            var currentPose = this.getState().Pose;
            this.resetPose(new Pose2d(currentPose.getX(), currentPose.getY(), new Rotation2d()));
        });
    }

    private final SwerveRequest.SwerveDriveBrake swerveBrake = new SwerveRequest.SwerveDriveBrake();

    public Command lockWheelsCommand() {
        return run(() -> {
            this.setControl(swerveBrake);
        });
    }

    public void lockWheels() {
        this.setControl(swerveBrake);
    }

    public Command testTriangle() {
        return new SequentialCommandGroup(goToPoseCommand(shooterPose1Red),
                goToPoseCommand(climbLeftRed),
                goToPoseCommand(climbRightRed),
                goToPoseCommand(shooterPose1Red));
    }

    public Command trenchRightOutCommand() {
        return new SequentialCommandGroup(
                goToPoseCommand(trenchRightCloseStartRed),
                goToPoseCommand(trenchRightFarEndRed));
    }

    public Command trenchRightInCommand() {
        return new SequentialCommandGroup(
                goToPoseCommand(trenchRightFarStartRed),
                goToPoseCommand(trenchRightCloseEndRed));
    }

    public Command trenchLeftOutCommand() {
        return new SequentialCommandGroup(
                goToPoseCommand(trenchLeftCloseStartRed),
                goToPoseCommand(trenchLeftFarEndRed));
    }

    public Command trenchLeftInCommand() {
        return new SequentialCommandGroup(
                goToPoseCommand(trenchLeftFarStartRed),
                goToPoseCommand(trenchLeftCloseEndRed));
    }

    public DeferredCommand bumpLeftOutCommand() {
        return new DeferredCommand(() -> {
            return new SequentialCommandGroup(
                    goToPoseCommand((bumpLeftClose), 2, 2),
                    goToPoseCommand((bumpLeftFar), 2, 2));
        }, new HashSet<Subsystem>(Arrays.asList(this)));
    }

    public DeferredCommand bumpLeftInCommand() {
        return new DeferredCommand(() -> {
            return new SequentialCommandGroup(
                    goToPoseCommand((bumpLeftFar), 2, 2),
                    goToPoseCommand((bumpLeftClose), 2, 2));
        }, new HashSet<Subsystem>(Arrays.asList(this)));
    }

    public DeferredCommand bumpRightOutCommand() {
        return new DeferredCommand(() -> {
            return new SequentialCommandGroup(
                    goToPoseCommand((bumpRightClose), 2, 2),
                    goToPoseCommand((bumpRightFar), 2, 2));
        }, new HashSet<Subsystem>(Arrays.asList(this)));
    }

    public DeferredCommand bumpRightInCommand() {
        return new DeferredCommand(() -> {
            return new SequentialCommandGroup(
                    goToPoseCommand((bumpRightFar), 2, 2),
                    goToPoseCommand((bumpRightClose), 2, 2));
        }, new HashSet<Subsystem>(Arrays.asList(this)));
    }

    public DeferredCommand bumpCommand() {
        return new DeferredCommand(() -> {
            var pose = this.getState().Pose;
            var hubMid = translatePose(hubMidPoint);
            var alliance = DriverStation.getAlliance().get();
            var isOut = (alliance == Alliance.Blue) ? pose.getX() < hubMid.getX()
                    : pose.getX() > hubMid.getX();
            // Determine Left or Right
            if ((alliance == Alliance.Red) ? pose.getY() > hubMid.getY() : pose.getY() < hubMid.getY()) {
                // is Right
                // Determine In or Out
                if (isOut) {
                    // is Out
                    return bumpRightOutCommand();
                } else {
                    // is In
                    return bumpRightInCommand();
                }
            } else {
                // is Left
                if (isOut) {
                    // is Out
                    return bumpLeftOutCommand();
                } else {
                    // is In
                    return bumpLeftInCommand();
                }
            }
        }, new HashSet<Subsystem>(Arrays.asList(this)));

    }

    public DeferredCommand trenchCommand() {
        return new DeferredCommand(() -> {
            var pose = this.getState().Pose;
            var hubMid = translatePose(hubMidPoint);
            var alliance = DriverStation.getAlliance().get();
            var isOut = (alliance == Alliance.Blue) ? pose.getX() < hubMid.getX()
                    : pose.getX() > hubMid.getX();
            // Determine Left or Right
            if ((alliance == Alliance.Red) ? pose.getY() > hubMid.getY() : pose.getY() < hubMid.getY()) {
                // is Right
                // Determine In or Out
                if (isOut) {
                    // is Out
                    return trenchRightOutCommand();
                } else {
                    // is In
                    return trenchRightInCommand();
                }
            } else {
                // is Left
                if (isOut) {
                    // is Out
                    return trenchLeftOutCommand();
                } else {
                    // is In
                    return trenchLeftInCommand();
                }
            }
        }, new HashSet<Subsystem>(Arrays.asList(this)));

    }

    public Command goToPoseCommand(Pose2d pose) {
        return goToPoseCommand(pose, 2, 1);
    }

    public Command goToPoseCommand(Pose2d pose, double maxVel, double maxAcc) {
        var traslatedPose = translatePose(pose);
        var cmd = AutoBuilder.pathfindToPose(traslatedPose, new PathConstraints(maxVel, maxAcc, 360,
                360));

        return cmd;
    }

    private Pose2d translatePose(Pose2d pose) {
        boolean isBlueAlliance = DriverStation.getAlliance().get() == Alliance.Blue;
        Pose2d newPose = new Pose2d(
                isBlueAlliance ? fieldLength - pose.getX() : pose.getX(),
                isBlueAlliance ? 8 - pose.getY() : pose.getY(),
                new Rotation2d(pose.getRotation().getRadians() + (isBlueAlliance ? Math.PI : 0)));
        return newPose;
    }

    public Command stopAllCommand() {
        return runOnce(() -> {
        });
    }

    private double distanceToHub() {
        var hubPose = translatePose(hubMidPoint);
        var robotPose = this.getState().Pose;
        var diff = hubPose.minus(robotPose);
        return Math.sqrt(diff.getX() * diff.getX() + diff.getY() * diff.getY());
    }

    public static final double ROTATE_KP_RAD_PER_SEC_PER_DEG = 0.06 * 180;
    public static final double ROTATE_MAX_OMEGA_RAD_PER_SEC = 4.0;
    public static final double ROTATE_DEADBAND_DEG = Units.degreesToRadians(1.0);

    public double angleToHubRobotReletive() {
        var currentPose = getState().Pose;
        var hubPoseX = fieldLength - 4.6;
        var hubPoseY = 4;

        var relativeX = hubPoseX - currentPose.getX();
        var relativeY = hubPoseY - currentPose.getY();
        var angleRad = Math.atan2(relativeY, relativeX) - currentPose.getRotation().getRadians();

        if (angleRad > Math.PI) {
            angleRad = angleRad - 2 * Math.PI;
        }
        return angleRad;
    }

    public double angleToHubFieldReletive() {
        var currentPose = getState().Pose;
        var hubPoseX = fieldLength - 4.6;
        var hubPoseY = 4;

        var relativeX = hubPoseX - currentPose.getX();
        var relativeY = hubPoseY - currentPose.getY();
        var angleRad = Math.atan2(relativeY, relativeX) - Math.PI;

        if (angleRad > Math.PI) {
            angleRad = angleRad - 2 * Math.PI;
        }
        return angleRad;
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                    () -> getState().Pose, // Supplier of current robot pose
                    this::resetPose, // Consumer for seeding pose against auto
                    () -> getState().Speeds, // Supplier of current robot speeds
                    // Consumer of ChassisSpeeds and feedforwards to drive the robot
                    (speeds, feedforwards) -> setControl(
                            m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                                    .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                                    .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
                    new PPHolonomicDriveController(
                            // PID constants for translation
                            new PIDConstants(8, 0, 0),
                            // PID constants for rotation
                            new PIDConstants(7, 0, 0)),
                    config,
                    // Assume the path needs to be flipped for Red vs Blue, this is normally the
                    // case
                    () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                    this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder",
                    ex.getStackTrace());
        }
    }

    /**
     * @deprecated
     * @return
     */
    public Command strafeWhileFiringCommand() {
        return run(() -> {
            var angleRad = angleToHubFieldReletive();
            SmartDashboard.putNumber("angle to hub", Units.radiansToDegrees(angleRad));
            this.setControl(
                    fieldCentric.withVelocityX(0)
                            .withVelocityY(.5)
                            .withHeadingPID(7, 0, 0)
                            .withTargetDirection(new Rotation2d(angleRad)));
        });
    }

    public double angleToHubAdjustedForVelocityFieldReletive() {
        var currentPose = getState().Pose;
        var speeds = getState().Speeds;
        var adjustedPose = currentPose
                .minus(new Pose2d(speeds.vxMetersPerSecond, speeds.vyMetersPerSecond, new Rotation2d()));
        var hubPoseX = fieldLength - 4.6;
        var hubPoseY = 4;

        var relativeX = hubPoseX - adjustedPose.getX();
        var relativeY = hubPoseY - adjustedPose.getY();
        var angleRad = Math.atan2(relativeY, relativeX) - Math.PI;

        if (angleRad > Math.PI) {
            angleRad = angleRad - 2 * Math.PI;
        }
        return angleRad;
    }

    public Command fireWhileDriving2(DoubleSupplier x, DoubleSupplier y) {
        return run(() -> {
            var targetPose = RobotContainer.launchingTower.getActualTarget();
            var robotPose = getState().Pose;

            // var angleRad = angleToHubAdjustedForVelocityFieldReletive();
            var angleRad = Math.atan2(targetPose.y - robotPose.getY(), targetPose.x - robotPose.getX());

            SmartDashboard.putNumber("angle to hub", Units.radiansToDegrees(angleRad));
            var joystickX = -x.getAsDouble();
            var joystickY = -y.getAsDouble();
            var d = Math.sqrt(joystickX * joystickX + joystickY * joystickY);
            // var vx = Math.cos(joystickX / d);
            // var vy = Math.sin(joystickY / d);
            var vx = joystickX / d;
            var vy = joystickY / d;

            // if we don't have a direction, lock the wheels
            if (Math.abs(joystickX) < .2 && Math.abs(joystickY) < .2) {
                this.setControl(swerveBrake);
            } else {
                this.setControl(
                        fieldCentric.withVelocityX(vx)
                                .withVelocityY(vy)
                                .withHeadingPID(7, 0, 0)
                                .withTargetDirection(new Rotation2d(angleRad)));
            }
        });
    }

    public Command fireWhileDriving(DoubleSupplier x, DoubleSupplier y) {
        return run(() -> {
            // var angleRad = angleToHubAdjustedForVelocityFieldReletive();
            var angleRad = fieldRelativeAngleToHubRad() + Math.PI;
            SmartDashboard.putNumber("angle to hub", Units.radiansToDegrees(angleRad));
            var joystickX = -x.getAsDouble();
            var joystickY = -y.getAsDouble();
            var d = Math.sqrt(joystickX * joystickX + joystickY * joystickY);
            // var vx = Math.cos(joystickX / d);
            // var vy = Math.sin(joystickY / d);
            var vx = joystickX / d;
            var vy = joystickY / d;
            var speed = 0.8;

            // if we don't have a direction, lock the wheels
            if (Math.abs(joystickX) < .2 && Math.abs(joystickY) < .2) {
                this.setControl(swerveBrake);
            } else {
                this.setControl(
                        fieldCentric.withVelocityX(vx * speed)
                                .withVelocityY(vy * speed)
                                .withHeadingPID(7, 0, 0)
                                .withTargetDirection(new Rotation2d(angleRad)));
            }
        });
    }

    public Command tankDrive(DoubleSupplier x, DoubleSupplier y) {
        return run(() -> {
            var joystickX = -x.getAsDouble();
            var joystickY = -y.getAsDouble();
            var vx = joystickX;
            var vy = joystickY;
            var maxSpeed = 4.0;

            var angleRad = Math.atan2(vy, vx);
            var speed = Math.sqrt(vx * vx + vy * vy);

            // if we don't have a direction, lock the wheels
            if (Math.abs(joystickX) < .2 && Math.abs(joystickY) < .2) {
                this.setControl(swerveBrake);
            } else {
                this.setControl(
                        fieldCentric.withVelocityX(vx * maxSpeed)
                                .withVelocityY(vy * maxSpeed)
                                .withHeadingPID(speed * 20, 0, 0)
                                .withTargetDirection(new Rotation2d(angleRad)));
            }
        });
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    Field2d field2d = new Field2d();

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }
        // add vision estimate
        var estimate = Vision.combineVisionEstemates(RobotContainer.visions, 2);
        if (estimate != null) {
            RobotContainer.drivetrain.addVisionMeasurement(estimate,
                    Timer.getFPGATimestamp());
        }

        SmartDashboard.putNumber("robot_position:x", this.getState().Pose.getX());
        SmartDashboard.putNumber("robot_position:y", this.getState().Pose.getY());
        SmartDashboard.putNumber("robot_position:rotation", this.getState().Pose.getRotation().getDegrees());
        var distance = distanceToHub();
        SmartDashboard.putNumber("distance_to_hub", distance);
        SmartDashboard.putNumber("hub offset", Units.radiansToDegrees(robotOffsetAngleToHubRad()));
        field.setRobotPose(getState().Pose);
        SmartDashboard.putData("Field", field);
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}